/* Umicom Kernel modern VirtIO MMIO block protocol constants.
 * Offsets and bits describe the published device protocol, not host C layout.
 * Only modern split queues and read requests are implemented. Spec references
 * and the supported subset are recorded in docs/READ_ONLY_VIRTIO_BLOCK.md.
 * Author: Sammy Hegab, Umicom Foundation. Licence: MIT. */
#ifndef UMICOM_KERNEL_VIRTIO_BLOCK_PROTOCOL_H
#define UMICOM_KERNEL_VIRTIO_BLOCK_PROTOCOL_H
#define UMICOM_VIRTIO_MAGIC 0x74726976U
#define UMICOM_VIRTIO_MMIO_MODERN 2U
#define UMICOM_VIRTIO_BLOCK_DEVICE 2U
#define UMICOM_VIRTIO_MAGIC_OFFSET 0x000U
#define UMICOM_VIRTIO_VERSION_OFFSET 0x004U
#define UMICOM_VIRTIO_DEVICE_ID 0x008U
#define UMICOM_VIRTIO_VENDOR_ID 0x00cU
#define UMICOM_VIRTIO_DEVICE_FEATURES 0x010U
#define UMICOM_VIRTIO_DEVICE_FEATURES_SELECT 0x014U
#define UMICOM_VIRTIO_DRIVER_FEATURES 0x020U
#define UMICOM_VIRTIO_DRIVER_FEATURES_SELECT 0x024U
#define UMICOM_VIRTIO_QUEUE_SELECT 0x030U
#define UMICOM_VIRTIO_QUEUE_MAX 0x034U
#define UMICOM_VIRTIO_QUEUE_SIZE 0x038U
#define UMICOM_VIRTIO_QUEUE_READY 0x044U
#define UMICOM_VIRTIO_QUEUE_NOTIFY 0x050U
#define UMICOM_VIRTIO_INTERRUPT_STATUS 0x060U
#define UMICOM_VIRTIO_INTERRUPT_ACK 0x064U
#define UMICOM_VIRTIO_STATUS 0x070U
#define UMICOM_VIRTIO_QUEUE_DESC_LOW 0x080U
#define UMICOM_VIRTIO_QUEUE_DESC_HIGH 0x084U
#define UMICOM_VIRTIO_QUEUE_AVAIL_LOW 0x090U
#define UMICOM_VIRTIO_QUEUE_AVAIL_HIGH 0x094U
#define UMICOM_VIRTIO_QUEUE_USED_LOW 0x0a0U
#define UMICOM_VIRTIO_QUEUE_USED_HIGH 0x0a4U
#define UMICOM_VIRTIO_CONFIG_GENERATION 0x0fcU
#define UMICOM_VIRTIO_CAPACITY_LOW 0x100U
#define UMICOM_VIRTIO_CAPACITY_HIGH 0x104U
#define UMICOM_VIRTIO_ACKNOWLEDGE 1U
#define UMICOM_VIRTIO_DRIVER 2U
#define UMICOM_VIRTIO_DRIVER_OK 4U
#define UMICOM_VIRTIO_FEATURES_OK 8U
#define UMICOM_VIRTIO_NEEDS_RESET 64U
#define UMICOM_VIRTIO_FAILED 128U
#define UMICOM_VIRTIO_READ_ONLY (1U << 5U)
#define UMICOM_VIRTIO_FEATURE_MODERN_HIGH 1U /* VIRTIO_F_VERSION_1 is feature bit 32. */
#define UMICOM_VIRTIO_RUNNING_STATUS 15U
#define UMICOM_VIRTIO_DESCRIPTOR_NEXT 1U
#define UMICOM_VIRTIO_DESCRIPTOR_WRITE 2U
#define UMICOM_VIRTIO_REQUEST_READ 0U
#define UMICOM_VIRTIO_RESULT_OK 0U
#define UMICOM_VIRTIO_RESULT_IO_ERROR 1U
#define UMICOM_VIRTIO_RESULT_UNSUPPORTED 2U
/* All queue areas fit one 4 KiB frame. The used ring does not share writable
 * bytes with the descriptor/available areas; alignment satisfies the protocol.
 * Header and status are separate descriptors even though they share this page. */
#define UMICOM_VIRTIO_DESC_BYTES 16U
#define UMICOM_VIRTIO_AVAIL_OFFSET 128U
#define UMICOM_VIRTIO_USED_OFFSET 256U
#define UMICOM_VIRTIO_HEADER_OFFSET 512U
#define UMICOM_VIRTIO_RESULT_OFFSET 528U
#define UMICOM_VIRTIO_HEADER_BYTES 16U
#endif /* UMICOM_KERNEL_VIRTIO_BLOCK_PROTOCOL_H */
