# Umicom Kernel persistent file lifecycle qualification.
# Six independently booted mutations/readers share one sequential clean image.
# Four checkpoint forks deliberately omit Finish for create/append/truncate/delete.
# Exact complete-media hashes and child protocol gates qualify every transition.
# Author: Sammy Hegab, Umicom Foundation. Licence: MIT.

set(UMICOM_FAT_LIFECYCLE_HASH_0_CLEAN "538d4c1def74b0241a91a350362038a85934a9a5d522f86bd7c5347b44c3e1b5")
set(UMICOM_FAT_LIFECYCLE_HASH_1_CLEAN "ebeab254cf3f3b655c4ee9ea7a9adb85e5d9d3a15c33746ae4e630735d0d3c1f")
set(UMICOM_FAT_LIFECYCLE_HASH_1_DIRTY "309b71a27164ad2c929a9bb6970c6408618a93ccebeca2c0ce737154697dcbc4")
set(UMICOM_FAT_LIFECYCLE_HASH_2_CLEAN "86b4ac59630125e1d880cfce2a64925ea3ce31b79c0770bc70bbca3ca9f4ce6f")
set(UMICOM_FAT_LIFECYCLE_HASH_2_DIRTY "4079f79b1faa4b2e140c998a0e7b20237df96ac2a3bb927dfed60b0e2b4777dc")
set(UMICOM_FAT_LIFECYCLE_HASH_3_CLEAN "1434a01ed8cafb84eebdefc8ff7d25d745e379b4c2a9e60641691895a3704cd6")
set(UMICOM_FAT_LIFECYCLE_HASH_3_DIRTY "4e318ff62c72a6270f132bf084aef8d89a8937d7ce232c0167b86dc4344084fa")
set(UMICOM_FAT_LIFECYCLE_HASH_4_CLEAN "801ce14f80fe28b65131fdfac8560f879f2b5e98e448d1f5dee17045c308e77c")
set(UMICOM_FAT_LIFECYCLE_HASH_4_DIRTY "3d00169747bc675ad3c1e3091bff62ae4514acc392d43f88fa8d21ad39465cde")
set(UMICOM_FAT_LIFECYCLE_HASH_5_CLEAN "e367ceb7958e5fd127ebd318f5ed481ea8f699e901c2320ad074bbf28f8418dd")
set(UMICOM_FAT_LIFECYCLE_HASH_6_CLEAN "b8f2d91a620d9b8ac69353a26401fe4d384421bbd4a4ae9f84f51c54978bef26")
set(UMICOM_FAT_LIFECYCLE_PHASES original create append truncate delete reuse empty-append)
if(CMAKE_SCRIPT_MODE_FILE)
    file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/../tests/fat16_file_commit/fixture.raw" UMICOM_FAT_LIFECYCLE_CHECKED_SOURCE)
    if(DEFINED UMICOM_FAT_LIFECYCLE_DISK AND EXISTS "${UMICOM_FAT_LIFECYCLE_DISK}")
        file(REAL_PATH "${UMICOM_FAT_LIFECYCLE_DISK}" UMICOM_FAT_LIFECYCLE_REAL_DISK)
        if(UMICOM_FAT_LIFECYCLE_REAL_DISK STREQUAL UMICOM_FAT_LIFECYCLE_CHECKED_SOURCE)
            message(FATAL_ERROR "The checked source cannot be a lifecycle disposable image.")
        endif()
    endif()
    if(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "cleanup")
        if(NOT DEFINED UMICOM_FAT_LIFECYCLE_DISK OR UMICOM_FAT_LIFECYCLE_DISK STREQUAL "")
            message(FATAL_ERROR "Lifecycle cleanup requires its disposable path.")
        endif()
        file(REMOVE "${UMICOM_FAT_LIFECYCLE_DISK}")
        if(EXISTS "${UMICOM_FAT_LIFECYCLE_DISK}")
            message(FATAL_ERROR "The lifecycle disposable copy remains after cleanup.")
        endif()
        message("fat16-lifecycle.cleanup=absent")
        return()
    endif()
    if(NOT DEFINED UMICOM_FAT_LIFECYCLE_STATE OR NOT UMICOM_FAT_LIFECYCLE_STATE MATCHES "^[0-6]$")
        message(FATAL_ERROR "Lifecycle state must be one integer from zero through six.")
    endif()
    if(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "prepare")
        if(NOT DEFINED UMICOM_FAT_LIFECYCLE_SOURCE OR NOT EXISTS "${UMICOM_FAT_LIFECYCLE_SOURCE}" OR
           NOT DEFINED UMICOM_FAT_LIFECYCLE_DISK OR UMICOM_FAT_LIFECYCLE_DISK STREQUAL "")
            message(FATAL_ERROR "Lifecycle prepare requires source and disposable paths.")
        endif()
        file(REAL_PATH "${UMICOM_FAT_LIFECYCLE_SOURCE}" UMICOM_FAT_LIFECYCLE_REAL_SOURCE)
        file(REAL_PATH "${UMICOM_FAT_LIFECYCLE_DISK}" UMICOM_FAT_LIFECYCLE_PREPARE_DISK)
        if(UMICOM_FAT_LIFECYCLE_REAL_SOURCE STREQUAL UMICOM_FAT_LIFECYCLE_PREPARE_DISK)
            message(FATAL_ERROR "Lifecycle prepare requires distinct real paths.")
        endif()
        file(SHA256 "${UMICOM_FAT_LIFECYCLE_SOURCE}" UMICOM_FAT_LIFECYCLE_HASH)
        if(NOT UMICOM_FAT_LIFECYCLE_HASH STREQUAL UMICOM_FAT_LIFECYCLE_HASH_${UMICOM_FAT_LIFECYCLE_STATE}_CLEAN)
            message(FATAL_ERROR "Lifecycle checkpoint source does not match its whole-image oracle.")
        endif()
        configure_file("${UMICOM_FAT_LIFECYCLE_SOURCE}" "${UMICOM_FAT_LIFECYCLE_DISK}" COPYONLY)
        file(SHA256 "${UMICOM_FAT_LIFECYCLE_DISK}" UMICOM_FAT_LIFECYCLE_COPY_HASH)
        if(NOT UMICOM_FAT_LIFECYCLE_COPY_HASH STREQUAL UMICOM_FAT_LIFECYCLE_HASH)
            message(FATAL_ERROR "Lifecycle checkpoint copy checksum mismatch.")
        endif()
        message("fat16-lifecycle.prepare=verified-checkpoint-${UMICOM_FAT_LIFECYCLE_STATE}")
        return()
    endif()
    foreach(UMICOM_FAT_LIFECYCLE_PATH IN ITEMS UMICOM_FAT_LIFECYCLE_QEMU UMICOM_FAT_LIFECYCLE_IMAGE UMICOM_FAT_LIFECYCLE_DISK)
        if(NOT DEFINED ${UMICOM_FAT_LIFECYCLE_PATH} OR NOT EXISTS "${${UMICOM_FAT_LIFECYCLE_PATH}}")
            message(FATAL_ERROR "Lifecycle runner requires existing ${UMICOM_FAT_LIFECYCLE_PATH}.")
        endif()
    endforeach()
    if(UMICOM_FAT_LIFECYCLE_DISK MATCHES "," OR UMICOM_FAT_LIFECYCLE_STATE EQUAL 0)
        message(FATAL_ERROR "Lifecycle run requires state1..6 and no drive-path comma.")
    endif()
    list(GET UMICOM_FAT_LIFECYCLE_PHASES ${UMICOM_FAT_LIFECYCLE_STATE} UMICOM_FAT_LIFECYCLE_PHASE)
    if(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "writer" OR UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "interrupted")
        math(EXPR UMICOM_FAT_LIFECYCLE_PREVIOUS "${UMICOM_FAT_LIFECYCLE_STATE} - 1")
        set(UMICOM_FAT_LIFECYCLE_BEFORE "${UMICOM_FAT_LIFECYCLE_HASH_${UMICOM_FAT_LIFECYCLE_PREVIOUS}_CLEAN}")
        if(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "writer")
            set(UMICOM_FAT_LIFECYCLE_MARKER UMICOM_KERNEL_FAT16_LIFECYCLE_READY)
            set(UMICOM_FAT_LIFECYCLE_AFTER "${UMICOM_FAT_LIFECYCLE_HASH_${UMICOM_FAT_LIFECYCLE_STATE}_CLEAN}")
        else()
            set(UMICOM_FAT_LIFECYCLE_MARKER UMICOM_KERNEL_FAT16_LIFECYCLE_INTERRUPTED_READY)
            set(UMICOM_FAT_LIFECYCLE_AFTER "${UMICOM_FAT_LIFECYCLE_HASH_${UMICOM_FAT_LIFECYCLE_STATE}_DIRTY}")
        endif()
        set(UMICOM_FAT_LIFECYCLE_DRIVE "file=${UMICOM_FAT_LIFECYCLE_DISK},if=none,format=raw,id=lifecycle,readonly=off,cache=writeback,rerror=report,werror=report")
        set(UMICOM_FAT_LIFECYCLE_DEVICE "virtio-blk-device,drive=lifecycle,write-cache=on,logical_block_size=512,physical_block_size=512,num-queues=1")
    elseif(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "readback" OR UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "rejected")
        if(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "readback")
            set(UMICOM_FAT_LIFECYCLE_MARKER UMICOM_KERNEL_FAT16_LIFECYCLE_READBACK_READY)
            set(UMICOM_FAT_LIFECYCLE_BEFORE "${UMICOM_FAT_LIFECYCLE_HASH_${UMICOM_FAT_LIFECYCLE_STATE}_CLEAN}")
        else()
            set(UMICOM_FAT_LIFECYCLE_MARKER UMICOM_KERNEL_FAT16_LIFECYCLE_REJECTED_READY)
            set(UMICOM_FAT_LIFECYCLE_BEFORE "${UMICOM_FAT_LIFECYCLE_HASH_${UMICOM_FAT_LIFECYCLE_STATE}_DIRTY}")
        endif()
        set(UMICOM_FAT_LIFECYCLE_AFTER "${UMICOM_FAT_LIFECYCLE_BEFORE}")
        set(UMICOM_FAT_LIFECYCLE_DRIVE "file=${UMICOM_FAT_LIFECYCLE_DISK},if=none,format=raw,id=lifecycle,readonly=on,cache=writeback,rerror=report")
        set(UMICOM_FAT_LIFECYCLE_DEVICE "virtio-blk-device,drive=lifecycle,logical_block_size=512,physical_block_size=512,num-queues=1")
    else()
        message(FATAL_ERROR "Lifecycle role must be writer, readback, interrupted or rejected.")
    endif()
    if((UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "interrupted" OR UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "rejected") AND UMICOM_FAT_LIFECYCLE_STATE GREATER 4)
        message(FATAL_ERROR "Lifecycle dirty roles require state1..4.")
    endif()
    file(SHA256 "${UMICOM_FAT_LIFECYCLE_DISK}" UMICOM_FAT_LIFECYCLE_BEFORE_HASH)
    message("fat16-lifecycle.image-before=${UMICOM_FAT_LIFECYCLE_BEFORE_HASH}")
    if(NOT UMICOM_FAT_LIFECYCLE_BEFORE_HASH STREQUAL UMICOM_FAT_LIFECYCLE_BEFORE)
        message(FATAL_ERROR "Lifecycle whole input image differs from its exact checkpoint.")
    endif()
    if(NOT DEFINED UMICOM_FAT_LIFECYCLE_RUN_TIMEOUT)
        set(UMICOM_FAT_LIFECYCLE_RUN_TIMEOUT 80)
    endif()
    if(NOT UMICOM_FAT_LIFECYCLE_RUN_TIMEOUT MATCHES "^[1-9][0-9]*$" OR UMICOM_FAT_LIFECYCLE_RUN_TIMEOUT GREATER 80)
        message(FATAL_ERROR "Lifecycle timeout must be an integer from1 through80 seconds.")
    endif()
    execute_process(COMMAND "${UMICOM_FAT_LIFECYCLE_QEMU}" -machine "virt,aclint=off"
        -bios "${UMICOM_FAT_LIFECYCLE_IMAGE}" -display none -monitor none -serial stdio
        -m 128M -smp 1 -no-reboot -global virtio-mmio.force-legacy=false
        -drive "${UMICOM_FAT_LIFECYCLE_DRIVE}" -device "${UMICOM_FAT_LIFECYCLE_DEVICE}"
        RESULT_VARIABLE UMICOM_FAT_LIFECYCLE_EXIT OUTPUT_VARIABLE UMICOM_FAT_LIFECYCLE_OUTPUT
        ERROR_VARIABLE UMICOM_FAT_LIFECYCLE_ERROR TIMEOUT "${UMICOM_FAT_LIFECYCLE_RUN_TIMEOUT}")
    message("${UMICOM_FAT_LIFECYCLE_OUTPUT}${UMICOM_FAT_LIFECYCLE_ERROR}")
    file(SHA256 "${UMICOM_FAT_LIFECYCLE_DISK}" UMICOM_FAT_LIFECYCLE_AFTER_HASH)
    message("fat16-lifecycle.image-after=${UMICOM_FAT_LIFECYCLE_AFTER_HASH}")
    if(NOT UMICOM_FAT_LIFECYCLE_AFTER_HASH STREQUAL UMICOM_FAT_LIFECYCLE_AFTER)
        message(FATAL_ERROR "Lifecycle whole output image differs from its exact oracle.")
    endif()
    if(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "readback" OR UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "rejected")
        message("fat16-lifecycle.backing-image=unchanged")
    else()
        message("fat16-lifecycle.backing-image=exact-lifecycle-result")
    endif()
    if(NOT UMICOM_FAT_LIFECYCLE_EXIT STREQUAL "0")
        message(FATAL_ERROR "Lifecycle guest did not exit successfully: ${UMICOM_FAT_LIFECYCLE_EXIT}")
    endif()
    string(REPLACE "\r\n" "\n" UMICOM_FAT_LIFECYCLE_TEXT "${UMICOM_FAT_LIFECYCLE_OUTPUT}${UMICOM_FAT_LIFECYCLE_ERROR}")
    if(UMICOM_FAT_LIFECYCLE_TEXT MATCHES "UMICOM_KERNEL_FAIL|unexpected-trap|panic|PANIC|failed|FAILED")
        message(FATAL_ERROR "Lifecycle guest emitted a failure marker.")
    endif()
    string(FIND "\n${UMICOM_FAT_LIFECYCLE_TEXT}\n" "\nfat16-lifecycle.phase=${UMICOM_FAT_LIFECYCLE_PHASE}\n" UMICOM_FAT_LIFECYCLE_PHASE_POSITION)
    string(FIND "\n${UMICOM_FAT_LIFECYCLE_TEXT}\n" "\n${UMICOM_FAT_LIFECYCLE_MARKER}\n" UMICOM_FAT_LIFECYCLE_READY_POSITION)
    string(FIND "\n${UMICOM_FAT_LIFECYCLE_TEXT}\n" "\nUMICOM_KERNEL_END\n" UMICOM_FAT_LIFECYCLE_END_POSITION)
    if(UMICOM_FAT_LIFECYCLE_PHASE_POSITION LESS 0 OR UMICOM_FAT_LIFECYCLE_READY_POSITION LESS UMICOM_FAT_LIFECYCLE_PHASE_POSITION OR
       UMICOM_FAT_LIFECYCLE_END_POSITION LESS UMICOM_FAT_LIFECYCLE_READY_POSITION)
        message(FATAL_ERROR "Lifecycle guest requires exact phase, readiness and end lines in order.")
    endif()
    return()
endif()

function(UmicomConfigureFat16LifecycleImages)
    if(NOT BUILD_TESTING)
        return()
    endif()
    # Snapshot the final Kernel source graph, including its shared updater and
    # firmware bridge. Each role changes only the dedicated entry selection.
    get_target_property(UMICOM_FAT_LIFECYCLE_SOURCES umicom-kernel SOURCES)
    get_target_property(UMICOM_FAT_LIFECYCLE_INCLUDES umicom-kernel INCLUDE_DIRECTORIES)
    get_target_property(UMICOM_FAT_LIFECYCLE_OPTIONS umicom-kernel COMPILE_OPTIONS)
    get_target_property(UMICOM_FAT_LIFECYCLE_LINK_OPTIONS umicom-kernel LINK_OPTIONS)
    get_target_property(UMICOM_FAT_LIFECYCLE_DEFINITIONS umicom-kernel COMPILE_DEFINITIONS)
    get_target_property(UMICOM_FAT_LIFECYCLE_LIBRARIES umicom-kernel LINK_LIBRARIES)
    get_target_property(UMICOM_FAT_LIFECYCLE_DEPENDENCIES umicom-kernel MANUALLY_ADDED_DEPENDENCIES)
    foreach(UMICOM_FAT_LIFECYCLE_ROLE IN ITEMS writer readback interrupted rejected)
        if(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "writer")
            set(UMICOM_FAT_LIFECYCLE_OUTPUT umicom-fat16-lifecycle)
            set(UMICOM_FAT_LIFECYCLE_DEFINITION UMICOM_KERNEL_FAT16_LIFECYCLE_TEST=1)
        elseif(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "readback")
            set(UMICOM_FAT_LIFECYCLE_OUTPUT umicom-fat16-lifecycle-readback)
            set(UMICOM_FAT_LIFECYCLE_DEFINITION UMICOM_KERNEL_FAT16_LIFECYCLE_READBACK_TEST=1)
        elseif(UMICOM_FAT_LIFECYCLE_ROLE STREQUAL "interrupted")
            set(UMICOM_FAT_LIFECYCLE_OUTPUT umicom-fat16-lifecycle-interrupted)
            set(UMICOM_FAT_LIFECYCLE_DEFINITION UMICOM_KERNEL_FAT16_LIFECYCLE_INTERRUPTED_TEST=1)
        else()
            set(UMICOM_FAT_LIFECYCLE_OUTPUT umicom-fat16-lifecycle-rejected)
            set(UMICOM_FAT_LIFECYCLE_DEFINITION UMICOM_KERNEL_FAT16_LIFECYCLE_REJECTED_TEST=1)
        endif()
        set(UMICOM_FAT_LIFECYCLE_TARGET "${UMICOM_FAT_LIFECYCLE_OUTPUT}-image")
        add_executable(${UMICOM_FAT_LIFECYCLE_TARGET} ${UMICOM_FAT_LIFECYCLE_SOURCES}
            "${CMAKE_CURRENT_SOURCE_DIR}/kernel/fat16_lifecycle_boot.c"
            "${CMAKE_CURRENT_SOURCE_DIR}/kernel/fat16_lifecycle_validation.c")
        target_include_directories(${UMICOM_FAT_LIFECYCLE_TARGET} PRIVATE ${UMICOM_FAT_LIFECYCLE_INCLUDES})
        target_compile_options(${UMICOM_FAT_LIFECYCLE_TARGET} PRIVATE ${UMICOM_FAT_LIFECYCLE_OPTIONS})
        target_compile_definitions(${UMICOM_FAT_LIFECYCLE_TARGET} PRIVATE ${UMICOM_FAT_LIFECYCLE_DEFINITION})
        if(UMICOM_FAT_LIFECYCLE_DEFINITIONS)
            target_compile_definitions(${UMICOM_FAT_LIFECYCLE_TARGET} PRIVATE ${UMICOM_FAT_LIFECYCLE_DEFINITIONS})
        endif()
        if(UMICOM_FAT_LIFECYCLE_LIBRARIES)
            target_link_libraries(${UMICOM_FAT_LIFECYCLE_TARGET} PRIVATE ${UMICOM_FAT_LIFECYCLE_LIBRARIES})
        endif()
        target_link_options(${UMICOM_FAT_LIFECYCLE_TARGET} PRIVATE ${UMICOM_FAT_LIFECYCLE_LINK_OPTIONS}
            "-Wl,-Map,${CMAKE_CURRENT_BINARY_DIR}/${UMICOM_FAT_LIFECYCLE_OUTPUT}.map")
        set_target_properties(${UMICOM_FAT_LIFECYCLE_TARGET} PROPERTIES OUTPUT_NAME "${UMICOM_FAT_LIFECYCLE_OUTPUT}"
            SUFFIX ".elf" RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/tests"
            LINK_DEPENDS "${UMICOM_KERNEL_LINKER_SCRIPT}")
        if(UMICOM_FAT_LIFECYCLE_DEPENDENCIES)
            add_dependencies(${UMICOM_FAT_LIFECYCLE_TARGET} ${UMICOM_FAT_LIFECYCLE_DEPENDENCIES})
        endif()
    endforeach()
    # Add reverse dependencies after all snapshots so clones cannot depend on
    # themselves. kernel_current_image rebuilds every acceptance executable.
    add_dependencies(umicom-kernel umicom-fat16-lifecycle-image umicom-fat16-lifecycle-readback-image
        umicom-fat16-lifecycle-interrupted-image umicom-fat16-lifecycle-rejected-image)
    if(NOT UMICOM_QEMU_RISCV64)
        return()
    endif()
    set(UMICOM_FAT_LIFECYCLE_FIXTURE_SOURCE "${CMAKE_CURRENT_SOURCE_DIR}/tests/fat16_file_commit/fixture.raw")
    file(SHA256 "${UMICOM_FAT_LIFECYCLE_FIXTURE_SOURCE}" UMICOM_FAT_LIFECYCLE_FIXTURE_HASH)
    if(NOT UMICOM_FAT_LIFECYCLE_FIXTURE_HASH STREQUAL "538d4c1def74b0241a91a350362038a85934a9a5d522f86bd7c5347b44c3e1b5")
        message(FATAL_ERROR "The synthetic archive-clear FAT16 fixture does not match its recorded SHA-256.")
    endif()
    set(UMICOM_FAT_LIFECYCLE_MAIN "${CMAKE_CURRENT_BINARY_DIR}/fixtures/umicom-fat16-lifecycle.raw")
    set(UMICOM_FAT_LIFECYCLE_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fat16Lifecycle.cmake")
    set(UMICOM_FAT_LIFECYCLE_BASE kernel.riscv64.fat16_lifecycle)
    add_test(NAME ${UMICOM_FAT_LIFECYCLE_BASE}_prepare COMMAND "${CMAKE_COMMAND}"
        "-DUMICOM_FAT_LIFECYCLE_SOURCE=${UMICOM_FAT_LIFECYCLE_FIXTURE_SOURCE}"
        "-DUMICOM_FAT_LIFECYCLE_DISK=${UMICOM_FAT_LIFECYCLE_MAIN}"
        -DUMICOM_FAT_LIFECYCLE_STATE=0 -DUMICOM_FAT_LIFECYCLE_ROLE=prepare -P "${UMICOM_FAT_LIFECYCLE_SCRIPT}")
    set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_prepare PROPERTIES TIMEOUT 10
        FIXTURES_REQUIRED kernel_current_image FIXTURES_SETUP kernel_fat16_lifecycle_fixture)
    set(UMICOM_FAT_LIFECYCLE_PREVIOUS kernel_fat16_lifecycle_fixture)
    foreach(UMICOM_FAT_LIFECYCLE_STATE RANGE 1 6)
        list(GET UMICOM_FAT_LIFECYCLE_PHASES ${UMICOM_FAT_LIFECYCLE_STATE} UMICOM_FAT_LIFECYCLE_PHASE)
        string(REPLACE "-" "_" UMICOM_FAT_LIFECYCLE_SUFFIX "${UMICOM_FAT_LIFECYCLE_PHASE}")
        set(UMICOM_FAT_LIFECYCLE_REQUIRED "kernel_current_image;kernel_fat16_lifecycle_fixture;${UMICOM_FAT_LIFECYCLE_PREVIOUS}")
        if(UMICOM_FAT_LIFECYCLE_STATE LESS 5)
            set(UMICOM_FAT_LIFECYCLE_FORK "${CMAKE_CURRENT_BINARY_DIR}/fixtures/umicom-fat16-lifecycle-${UMICOM_FAT_LIFECYCLE_PHASE}-interrupted.raw")
            set(UMICOM_FAT_LIFECYCLE_FORK_ID "kernel_fat16_lifecycle_${UMICOM_FAT_LIFECYCLE_SUFFIX}_fork")
            set(UMICOM_FAT_LIFECYCLE_STAGED_ID "${UMICOM_FAT_LIFECYCLE_FORK_ID}_staged")
            math(EXPR UMICOM_FAT_LIFECYCLE_SOURCE_STATE "${UMICOM_FAT_LIFECYCLE_STATE} - 1")
            add_test(NAME ${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_fork_prepare COMMAND "${CMAKE_COMMAND}"
                "-DUMICOM_FAT_LIFECYCLE_SOURCE=${UMICOM_FAT_LIFECYCLE_MAIN}" "-DUMICOM_FAT_LIFECYCLE_DISK=${UMICOM_FAT_LIFECYCLE_FORK}"
                "-DUMICOM_FAT_LIFECYCLE_STATE=${UMICOM_FAT_LIFECYCLE_SOURCE_STATE}" -DUMICOM_FAT_LIFECYCLE_ROLE=prepare -P "${UMICOM_FAT_LIFECYCLE_SCRIPT}")
            set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_fork_prepare PROPERTIES TIMEOUT 10
                FIXTURES_REQUIRED "${UMICOM_FAT_LIFECYCLE_REQUIRED}" FIXTURES_SETUP "${UMICOM_FAT_LIFECYCLE_FORK_ID}")
            # The main writer cannot mutate this checkpoint until the dirty
            # fork's prepare has copied and hashed every byte successfully.
            list(APPEND UMICOM_FAT_LIFECYCLE_REQUIRED "${UMICOM_FAT_LIFECYCLE_FORK_ID}")
            foreach(UMICOM_FAT_LIFECYCLE_FORK_ROLE IN ITEMS interrupted rejected)
                if(UMICOM_FAT_LIFECYCLE_FORK_ROLE STREQUAL "interrupted")
                    set(UMICOM_FAT_LIFECYCLE_FORK_DEPENDENCY "${UMICOM_FAT_LIFECYCLE_FORK_ID}")
                else()
                    set(UMICOM_FAT_LIFECYCLE_FORK_DEPENDENCY "${UMICOM_FAT_LIFECYCLE_FORK_ID};${UMICOM_FAT_LIFECYCLE_STAGED_ID}")
                endif()
                add_test(NAME ${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_${UMICOM_FAT_LIFECYCLE_FORK_ROLE}
                    COMMAND "${CMAKE_COMMAND}" "-DUMICOM_FAT_LIFECYCLE_QEMU=${UMICOM_QEMU_RISCV64}"
                    "-DUMICOM_FAT_LIFECYCLE_IMAGE=$<TARGET_FILE:umicom-fat16-lifecycle-${UMICOM_FAT_LIFECYCLE_FORK_ROLE}-image>"
                    "-DUMICOM_FAT_LIFECYCLE_DISK=${UMICOM_FAT_LIFECYCLE_FORK}" "-DUMICOM_FAT_LIFECYCLE_STATE=${UMICOM_FAT_LIFECYCLE_STATE}"
                    "-DUMICOM_FAT_LIFECYCLE_ROLE=${UMICOM_FAT_LIFECYCLE_FORK_ROLE}" -P "${UMICOM_FAT_LIFECYCLE_SCRIPT}")
                set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_${UMICOM_FAT_LIFECYCLE_FORK_ROLE}
                    PROPERTIES TIMEOUT 90 FIXTURES_REQUIRED "kernel_current_image;${UMICOM_FAT_LIFECYCLE_FORK_DEPENDENCY}")
                if(UMICOM_FAT_LIFECYCLE_FORK_ROLE STREQUAL "interrupted")
                    set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_interrupted
                        PROPERTIES FIXTURES_SETUP "${UMICOM_FAT_LIFECYCLE_STAGED_ID}")
                endif()
            endforeach()
            add_test(NAME ${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_fork_cleanup COMMAND "${CMAKE_COMMAND}"
                "-DUMICOM_FAT_LIFECYCLE_DISK=${UMICOM_FAT_LIFECYCLE_FORK}" -DUMICOM_FAT_LIFECYCLE_ROLE=cleanup -P "${UMICOM_FAT_LIFECYCLE_SCRIPT}")
            set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_fork_cleanup
                PROPERTIES TIMEOUT 10 FIXTURES_CLEANUP "${UMICOM_FAT_LIFECYCLE_FORK_ID}")
        endif()
        add_test(NAME ${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX} COMMAND "${CMAKE_COMMAND}"
            "-DUMICOM_FAT_LIFECYCLE_QEMU=${UMICOM_QEMU_RISCV64}" "-DUMICOM_FAT_LIFECYCLE_IMAGE=$<TARGET_FILE:umicom-fat16-lifecycle-image>"
            "-DUMICOM_FAT_LIFECYCLE_DISK=${UMICOM_FAT_LIFECYCLE_MAIN}" "-DUMICOM_FAT_LIFECYCLE_STATE=${UMICOM_FAT_LIFECYCLE_STATE}"
            -DUMICOM_FAT_LIFECYCLE_ROLE=writer -P "${UMICOM_FAT_LIFECYCLE_SCRIPT}")
        set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX} PROPERTIES TIMEOUT 90
            FIXTURES_REQUIRED "${UMICOM_FAT_LIFECYCLE_REQUIRED}" FIXTURES_SETUP "kernel_fat16_lifecycle_clean_${UMICOM_FAT_LIFECYCLE_STATE}")
        add_test(NAME ${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_readback COMMAND "${CMAKE_COMMAND}"
            "-DUMICOM_FAT_LIFECYCLE_QEMU=${UMICOM_QEMU_RISCV64}" "-DUMICOM_FAT_LIFECYCLE_IMAGE=$<TARGET_FILE:umicom-fat16-lifecycle-readback-image>"
            "-DUMICOM_FAT_LIFECYCLE_DISK=${UMICOM_FAT_LIFECYCLE_MAIN}" "-DUMICOM_FAT_LIFECYCLE_STATE=${UMICOM_FAT_LIFECYCLE_STATE}"
            -DUMICOM_FAT_LIFECYCLE_ROLE=readback -P "${UMICOM_FAT_LIFECYCLE_SCRIPT}")
        set(UMICOM_FAT_LIFECYCLE_PREVIOUS "kernel_fat16_lifecycle_validated_${UMICOM_FAT_LIFECYCLE_STATE}")
        set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_${UMICOM_FAT_LIFECYCLE_SUFFIX}_readback PROPERTIES TIMEOUT 90
            FIXTURES_REQUIRED "kernel_current_image;kernel_fat16_lifecycle_fixture;kernel_fat16_lifecycle_clean_${UMICOM_FAT_LIFECYCLE_STATE}"
            FIXTURES_SETUP "${UMICOM_FAT_LIFECYCLE_PREVIOUS}")
    endforeach()
    add_test(NAME ${UMICOM_FAT_LIFECYCLE_BASE}_cleanup COMMAND "${CMAKE_COMMAND}"
        "-DUMICOM_FAT_LIFECYCLE_DISK=${UMICOM_FAT_LIFECYCLE_MAIN}" -DUMICOM_FAT_LIFECYCLE_ROLE=cleanup -P "${UMICOM_FAT_LIFECYCLE_SCRIPT}")
    set_tests_properties(${UMICOM_FAT_LIFECYCLE_BASE}_cleanup PROPERTIES TIMEOUT 10 FIXTURES_CLEANUP kernel_fat16_lifecycle_fixture)
endfunction()
cmake_language(DEFER CALL UmicomConfigureFat16LifecycleImages)
