# Umicom Kernel persistent file directory qualification.
# Nine independently booted mutations/readers share one sequential clean image.
# Nine checkpoint forks deliberately omit Finish for directory and file operations.
# Exact complete-media hashes and child protocol gates qualify every transition.
# Author: Sammy Hegab, Umicom Foundation. Licence: MIT.

set(UMICOM_FAT_DIRECTORY_HASH_0_CLEAN "538d4c1def74b0241a91a350362038a85934a9a5d522f86bd7c5347b44c3e1b5")
set(UMICOM_FAT_DIRECTORY_HASH_1_CLEAN "f38a80f630145e9219bbb5c734db2387b555ec88a175579fc3bd0239b02c334d")
set(UMICOM_FAT_DIRECTORY_HASH_1_DIRTY "ba10da3cd899be47007322615c4a490d88de53013d1fa5fea1978175ac9db4cf")
set(UMICOM_FAT_DIRECTORY_HASH_2_CLEAN "7259c10e6fedf51c12b0e9f8c56c0a3facb3d1065e82b742e90385099fcc7dcd")
set(UMICOM_FAT_DIRECTORY_HASH_2_DIRTY "799682321739d71597d656de8abe7a84bf2279d9a428abcc989e1c911d76ef52")
set(UMICOM_FAT_DIRECTORY_HASH_3_CLEAN "f4629266f68a3f1daa9c977aeb7b3364e09f281e5664782fbaeb0f6435bb8e78")
set(UMICOM_FAT_DIRECTORY_HASH_3_DIRTY "212e6aefd2f904871138dd1e931c3ea6872a5f66e0a92358f8ce13f0c896cbc6")
set(UMICOM_FAT_DIRECTORY_HASH_4_CLEAN "7e8b6379e16c30618e4901a6261d31bb1d2a477aa03f4fd270dd5f7a8e5470be")
set(UMICOM_FAT_DIRECTORY_HASH_4_DIRTY "6da5c69d1fd4f89fbce14783eb94102969036f9f7129dc9c1973e131c3ebad40")
set(UMICOM_FAT_DIRECTORY_HASH_5_CLEAN "0fa79f3b29a64a2f7e79fe2192292ee682c5493812b86f5b0c603d5c7161f017")
set(UMICOM_FAT_DIRECTORY_HASH_5_DIRTY "72154787757c1c9c6a0e555e2dfceed80bd53b98b94f10cbacf1f59477225371")
set(UMICOM_FAT_DIRECTORY_HASH_6_CLEAN "7237b44db29643cee30c8e35b283d87295ef6c3d7d96aa3894e66e4224324d46")
set(UMICOM_FAT_DIRECTORY_HASH_6_DIRTY "ff2fb996ec728859e094b2d51fbfc62db2761767328e0a0944beba7098aff7b2")
set(UMICOM_FAT_DIRECTORY_HASH_7_CLEAN "2d7dcf2f3cdbcad6439ff444c1640b01b2c70e64a9ffb4c9c136213161f0003c")
set(UMICOM_FAT_DIRECTORY_HASH_7_DIRTY "f753266395364068a5cc67f1570797c50b9f3c541b5e0c52260d7b02609d64df")
set(UMICOM_FAT_DIRECTORY_HASH_8_CLEAN "b2aeb41d7d48ed48c3f9c217247c1f79955cf4ecc2107ac0ab8243028002451b")
set(UMICOM_FAT_DIRECTORY_HASH_8_DIRTY "421d08210e2963d96ec4cd70ea3374eeb42775b92ef06cc32056f544186e367d")
set(UMICOM_FAT_DIRECTORY_HASH_9_CLEAN "5a4ed48e3ce8e8116ea65d7f7c416c27ec92670ae3493f50768dff3ef3ee97d0")
set(UMICOM_FAT_DIRECTORY_HASH_9_DIRTY "1d0e567d0c92d2ccecda86112cda310f6cdaadfb16ac7033f388c13d34ebc951")
set(UMICOM_FAT_DIRECTORY_HASH_10_CLEAN "61f699964639842ddb3811e07e8e6a21a5d764ad062de89ad793a7cf6ab60ad5")
set(UMICOM_FAT_DIRECTORY_HASH_10_DIRTY "d5143af57f55489d69f53a181a357c6ee9e0afb015d08b5afd0bce04c96a3862")
set(UMICOM_FAT_DIRECTORY_HASH_11_CLEAN "77270c91bf4b29df7d73328ae099ad505ff72338883089a4ed019586b36b8654")
set(UMICOM_FAT_DIRECTORY_HASH_11_DIRTY "a713043744fb78e3f75f35286f24bb4f60813780bfe442a12fc368219d625569")
set(UMICOM_FAT_DIRECTORY_HASH_12_CLEAN "168d2a8452dd12cc10dc893aaed33ba0e72eb85b322e760b6948ac7f0b7683a7")
set(UMICOM_FAT_DIRECTORY_HASH_12_DIRTY "7b843ccaac298bbe97793024976fc17e8016f1724b4bac91877f9cf12dc4704f")
set(UMICOM_FAT_DIRECTORY_HASH_13_CLEAN "42001d058626189dd8c457d03ad3709859b1c1047ed0dc5dcf32b2ba8dc18d57")
set(UMICOM_FAT_DIRECTORY_HASH_13_DIRTY "1987805aeb4dc238146edcd43b65bdd22b244a0bc4d93a8ed55b4006893683f0")
# Existing phases remain; move phases extend the same fixture chain.
set(UMICOM_FAT_DIRECTORY_PHASES original mkdir nested create append delete rmdir-nested rmdir reuse growth move-tree move-root rename-tree move-file)
if(CMAKE_SCRIPT_MODE_FILE)
    file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/../tests/fat16_file_commit/fixture.raw" UMICOM_FAT_DIRECTORY_CHECKED_SOURCE)
    if(DEFINED UMICOM_FAT_DIRECTORY_DISK AND EXISTS "${UMICOM_FAT_DIRECTORY_DISK}")
        file(REAL_PATH "${UMICOM_FAT_DIRECTORY_DISK}" UMICOM_FAT_DIRECTORY_REAL_DISK)
        if(UMICOM_FAT_DIRECTORY_REAL_DISK STREQUAL UMICOM_FAT_DIRECTORY_CHECKED_SOURCE)
            message(FATAL_ERROR "The checked source cannot be a directory disposable image.")
        endif()
    endif()
    if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "cleanup")
        if(NOT DEFINED UMICOM_FAT_DIRECTORY_DISK OR UMICOM_FAT_DIRECTORY_DISK STREQUAL "")
            message(FATAL_ERROR "Directory cleanup requires its disposable path.")
        endif()
        file(REMOVE "${UMICOM_FAT_DIRECTORY_DISK}")
        if(EXISTS "${UMICOM_FAT_DIRECTORY_DISK}")
            message(FATAL_ERROR "The directory disposable copy remains after cleanup.")
        endif()
        message("fat16-directory.cleanup=absent")
        return()
    endif()
    if(NOT DEFINED UMICOM_FAT_DIRECTORY_STATE OR NOT UMICOM_FAT_DIRECTORY_STATE MATCHES "^([0-9]|1[0-3])$")
        message(FATAL_ERROR "Directory state must be one integer from zero through thirteen.")
    endif()
    if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "prepare")
        if(NOT DEFINED UMICOM_FAT_DIRECTORY_SOURCE OR NOT EXISTS "${UMICOM_FAT_DIRECTORY_SOURCE}" OR
           NOT DEFINED UMICOM_FAT_DIRECTORY_DISK OR UMICOM_FAT_DIRECTORY_DISK STREQUAL "")
            message(FATAL_ERROR "Directory prepare requires source and disposable paths.")
        endif()
        file(REAL_PATH "${UMICOM_FAT_DIRECTORY_SOURCE}" UMICOM_FAT_DIRECTORY_REAL_SOURCE)
        file(REAL_PATH "${UMICOM_FAT_DIRECTORY_DISK}" UMICOM_FAT_DIRECTORY_PREPARE_DISK)
        if(UMICOM_FAT_DIRECTORY_REAL_SOURCE STREQUAL UMICOM_FAT_DIRECTORY_PREPARE_DISK)
            message(FATAL_ERROR "Directory prepare requires distinct real paths.")
        endif()
        file(SHA256 "${UMICOM_FAT_DIRECTORY_SOURCE}" UMICOM_FAT_DIRECTORY_HASH)
        if(NOT UMICOM_FAT_DIRECTORY_HASH STREQUAL UMICOM_FAT_DIRECTORY_HASH_${UMICOM_FAT_DIRECTORY_STATE}_CLEAN)
            message(FATAL_ERROR "Directory checkpoint source does not match its whole-image oracle.")
        endif()
        configure_file("${UMICOM_FAT_DIRECTORY_SOURCE}" "${UMICOM_FAT_DIRECTORY_DISK}" COPYONLY)
        file(SHA256 "${UMICOM_FAT_DIRECTORY_DISK}" UMICOM_FAT_DIRECTORY_COPY_HASH)
        if(NOT UMICOM_FAT_DIRECTORY_COPY_HASH STREQUAL UMICOM_FAT_DIRECTORY_HASH)
            message(FATAL_ERROR "Directory checkpoint copy checksum mismatch.")
        endif()
        message("fat16-directory.prepare=verified-checkpoint-${UMICOM_FAT_DIRECTORY_STATE}")
        return()
    endif()
    foreach(UMICOM_FAT_DIRECTORY_PATH IN ITEMS UMICOM_FAT_DIRECTORY_QEMU UMICOM_FAT_DIRECTORY_IMAGE UMICOM_FAT_DIRECTORY_DISK)
        if(NOT DEFINED ${UMICOM_FAT_DIRECTORY_PATH} OR NOT EXISTS "${${UMICOM_FAT_DIRECTORY_PATH}}")
            message(FATAL_ERROR "Directory runner requires existing ${UMICOM_FAT_DIRECTORY_PATH}.")
        endif()
    endforeach()
    if(UMICOM_FAT_DIRECTORY_DISK MATCHES "," OR UMICOM_FAT_DIRECTORY_STATE EQUAL 0)
        message(FATAL_ERROR "Directory run requires states 1..13 and no drive-path comma.")
    endif()
    list(GET UMICOM_FAT_DIRECTORY_PHASES ${UMICOM_FAT_DIRECTORY_STATE} UMICOM_FAT_DIRECTORY_PHASE)
    if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "writer" OR UMICOM_FAT_DIRECTORY_ROLE STREQUAL "interrupted")
        math(EXPR UMICOM_FAT_DIRECTORY_PREVIOUS "${UMICOM_FAT_DIRECTORY_STATE} - 1")
        set(UMICOM_FAT_DIRECTORY_BEFORE "${UMICOM_FAT_DIRECTORY_HASH_${UMICOM_FAT_DIRECTORY_PREVIOUS}_CLEAN}")
        if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "writer")
            set(UMICOM_FAT_DIRECTORY_MARKER UMICOM_KERNEL_FAT16_DIRECTORY_READY)
            set(UMICOM_FAT_DIRECTORY_AFTER "${UMICOM_FAT_DIRECTORY_HASH_${UMICOM_FAT_DIRECTORY_STATE}_CLEAN}")
        else()
            set(UMICOM_FAT_DIRECTORY_MARKER UMICOM_KERNEL_FAT16_DIRECTORY_INTERRUPTED_READY)
            set(UMICOM_FAT_DIRECTORY_AFTER "${UMICOM_FAT_DIRECTORY_HASH_${UMICOM_FAT_DIRECTORY_STATE}_DIRTY}")
        endif()
        set(UMICOM_FAT_DIRECTORY_DRIVE "file=${UMICOM_FAT_DIRECTORY_DISK},if=none,format=raw,id=directory,readonly=off,cache=writeback,rerror=report,werror=report")
        set(UMICOM_FAT_DIRECTORY_DEVICE "virtio-blk-device,drive=directory,write-cache=on,logical_block_size=512,physical_block_size=512,num-queues=1")
    elseif(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "readback" OR UMICOM_FAT_DIRECTORY_ROLE STREQUAL "rejected")
        if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "readback")
            set(UMICOM_FAT_DIRECTORY_MARKER UMICOM_KERNEL_FAT16_DIRECTORY_READBACK_READY)
            set(UMICOM_FAT_DIRECTORY_BEFORE "${UMICOM_FAT_DIRECTORY_HASH_${UMICOM_FAT_DIRECTORY_STATE}_CLEAN}")
        else()
            set(UMICOM_FAT_DIRECTORY_MARKER UMICOM_KERNEL_FAT16_DIRECTORY_REJECTED_READY)
            set(UMICOM_FAT_DIRECTORY_BEFORE "${UMICOM_FAT_DIRECTORY_HASH_${UMICOM_FAT_DIRECTORY_STATE}_DIRTY}")
        endif()
        set(UMICOM_FAT_DIRECTORY_AFTER "${UMICOM_FAT_DIRECTORY_BEFORE}")
        set(UMICOM_FAT_DIRECTORY_DRIVE "file=${UMICOM_FAT_DIRECTORY_DISK},if=none,format=raw,id=directory,readonly=on,cache=writeback,rerror=report")
        set(UMICOM_FAT_DIRECTORY_DEVICE "virtio-blk-device,drive=directory,logical_block_size=512,physical_block_size=512,num-queues=1")
    else()
        message(FATAL_ERROR "Directory role must be writer, readback, interrupted or rejected.")
    endif()
    if((UMICOM_FAT_DIRECTORY_ROLE STREQUAL "interrupted" OR UMICOM_FAT_DIRECTORY_ROLE STREQUAL "rejected") AND UMICOM_FAT_DIRECTORY_STATE GREATER 13)
        message(FATAL_ERROR "Directory dirty roles require states 1..13.")
    endif()
    file(SHA256 "${UMICOM_FAT_DIRECTORY_DISK}" UMICOM_FAT_DIRECTORY_BEFORE_HASH)
    message("fat16-directory.image-before=${UMICOM_FAT_DIRECTORY_BEFORE_HASH}")
    if(NOT UMICOM_FAT_DIRECTORY_BEFORE_HASH STREQUAL UMICOM_FAT_DIRECTORY_BEFORE)
        message(FATAL_ERROR "Directory whole input image differs from its exact checkpoint.")
    endif()
    if(NOT DEFINED UMICOM_FAT_DIRECTORY_RUN_TIMEOUT)
        set(UMICOM_FAT_DIRECTORY_RUN_TIMEOUT 80)
    endif()
    if(NOT UMICOM_FAT_DIRECTORY_RUN_TIMEOUT MATCHES "^[1-9][0-9]*$" OR UMICOM_FAT_DIRECTORY_RUN_TIMEOUT GREATER 80)
        message(FATAL_ERROR "Directory timeout must be an integer from1 through80 seconds.")
    endif()
    execute_process(COMMAND "${UMICOM_FAT_DIRECTORY_QEMU}" -machine "virt,aclint=off"
        -bios "${UMICOM_FAT_DIRECTORY_IMAGE}" -display none -monitor none -serial stdio
        -m 128M -smp 1 -no-reboot -global virtio-mmio.force-legacy=false
        -drive "${UMICOM_FAT_DIRECTORY_DRIVE}" -device "${UMICOM_FAT_DIRECTORY_DEVICE}"
        RESULT_VARIABLE UMICOM_FAT_DIRECTORY_EXIT OUTPUT_VARIABLE UMICOM_FAT_DIRECTORY_OUTPUT
        ERROR_VARIABLE UMICOM_FAT_DIRECTORY_ERROR TIMEOUT "${UMICOM_FAT_DIRECTORY_RUN_TIMEOUT}")
    message("${UMICOM_FAT_DIRECTORY_OUTPUT}${UMICOM_FAT_DIRECTORY_ERROR}")
    file(SHA256 "${UMICOM_FAT_DIRECTORY_DISK}" UMICOM_FAT_DIRECTORY_AFTER_HASH)
    message("fat16-directory.image-after=${UMICOM_FAT_DIRECTORY_AFTER_HASH}")
    if(NOT UMICOM_FAT_DIRECTORY_AFTER_HASH STREQUAL UMICOM_FAT_DIRECTORY_AFTER)
        message(FATAL_ERROR "Directory whole output image differs from its exact oracle.")
    endif()
    if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "readback" OR UMICOM_FAT_DIRECTORY_ROLE STREQUAL "rejected")
        message("fat16-directory.backing-image=unchanged")
    else()
        message("fat16-directory.backing-image=exact-directory-result")
    endif()
    if(NOT UMICOM_FAT_DIRECTORY_EXIT STREQUAL "0")
        message(FATAL_ERROR "Directory guest did not exit successfully: ${UMICOM_FAT_DIRECTORY_EXIT}")
    endif()
    string(REPLACE "\r\n" "\n" UMICOM_FAT_DIRECTORY_TEXT "${UMICOM_FAT_DIRECTORY_OUTPUT}${UMICOM_FAT_DIRECTORY_ERROR}")
    if(UMICOM_FAT_DIRECTORY_TEXT MATCHES "UMICOM_KERNEL_FAIL|unexpected-trap|panic|PANIC|failed|FAILED")
        message(FATAL_ERROR "Directory guest emitted a failure marker.")
    endif()
    if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "writer" AND
       NOT UMICOM_FAT_DIRECTORY_TEXT MATCHES "fat16-directory.committed-inspection=verified")
        message(FATAL_ERROR "Directory writer did not verify committed inspection.")
    endif()
    string(FIND "\n${UMICOM_FAT_DIRECTORY_TEXT}\n" "\nfat16-directory.phase=${UMICOM_FAT_DIRECTORY_PHASE}\n" UMICOM_FAT_DIRECTORY_PHASE_POSITION)
    string(FIND "\n${UMICOM_FAT_DIRECTORY_TEXT}\n" "\n${UMICOM_FAT_DIRECTORY_MARKER}\n" UMICOM_FAT_DIRECTORY_READY_POSITION)
    string(FIND "\n${UMICOM_FAT_DIRECTORY_TEXT}\n" "\nUMICOM_KERNEL_END\n" UMICOM_FAT_DIRECTORY_END_POSITION)
    if(UMICOM_FAT_DIRECTORY_PHASE_POSITION LESS 0 OR UMICOM_FAT_DIRECTORY_READY_POSITION LESS UMICOM_FAT_DIRECTORY_PHASE_POSITION OR
       UMICOM_FAT_DIRECTORY_END_POSITION LESS UMICOM_FAT_DIRECTORY_READY_POSITION)
        message(FATAL_ERROR "Directory guest requires exact phase, readiness and end lines in order.")
    endif()
    return()
endif()

function(UmicomConfigureFat16DirectoryImages)
    if(NOT BUILD_TESTING)
        return()
    endif()
    # Snapshot the final Kernel source graph, including its shared updater and
    # firmware bridge. Each role changes only the dedicated entry selection.
    get_target_property(UMICOM_FAT_DIRECTORY_SOURCES umicom-kernel SOURCES)
    get_target_property(UMICOM_FAT_DIRECTORY_INCLUDES umicom-kernel INCLUDE_DIRECTORIES)
    get_target_property(UMICOM_FAT_DIRECTORY_OPTIONS umicom-kernel COMPILE_OPTIONS)
    get_target_property(UMICOM_FAT_DIRECTORY_LINK_OPTIONS umicom-kernel LINK_OPTIONS)
    get_target_property(UMICOM_FAT_DIRECTORY_DEFINITIONS umicom-kernel COMPILE_DEFINITIONS)
    get_target_property(UMICOM_FAT_DIRECTORY_LIBRARIES umicom-kernel LINK_LIBRARIES)
    get_target_property(UMICOM_FAT_DIRECTORY_DEPENDENCIES umicom-kernel MANUALLY_ADDED_DEPENDENCIES)
    foreach(UMICOM_FAT_DIRECTORY_ROLE IN ITEMS writer readback interrupted rejected)
        if(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "writer")
            set(UMICOM_FAT_DIRECTORY_OUTPUT umicom-fat16-directory)
            set(UMICOM_FAT_DIRECTORY_DEFINITION UMICOM_KERNEL_FAT16_DIRECTORY_TEST=1)
        elseif(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "readback")
            set(UMICOM_FAT_DIRECTORY_OUTPUT umicom-fat16-directory-readback)
            set(UMICOM_FAT_DIRECTORY_DEFINITION UMICOM_KERNEL_FAT16_DIRECTORY_READBACK_TEST=1)
        elseif(UMICOM_FAT_DIRECTORY_ROLE STREQUAL "interrupted")
            set(UMICOM_FAT_DIRECTORY_OUTPUT umicom-fat16-directory-interrupted)
            set(UMICOM_FAT_DIRECTORY_DEFINITION UMICOM_KERNEL_FAT16_DIRECTORY_INTERRUPTED_TEST=1)
        else()
            set(UMICOM_FAT_DIRECTORY_OUTPUT umicom-fat16-directory-rejected)
            set(UMICOM_FAT_DIRECTORY_DEFINITION UMICOM_KERNEL_FAT16_DIRECTORY_REJECTED_TEST=1)
        endif()
        set(UMICOM_FAT_DIRECTORY_TARGET "${UMICOM_FAT_DIRECTORY_OUTPUT}-image")
        add_executable(${UMICOM_FAT_DIRECTORY_TARGET} ${UMICOM_FAT_DIRECTORY_SOURCES}
            "${CMAKE_CURRENT_SOURCE_DIR}/kernel/fat16_directory_boot.c"
            "${CMAKE_CURRENT_SOURCE_DIR}/kernel/fat16_directory_validation.c")
        target_include_directories(${UMICOM_FAT_DIRECTORY_TARGET} PRIVATE ${UMICOM_FAT_DIRECTORY_INCLUDES})
        target_compile_options(${UMICOM_FAT_DIRECTORY_TARGET} PRIVATE ${UMICOM_FAT_DIRECTORY_OPTIONS})
        target_compile_definitions(${UMICOM_FAT_DIRECTORY_TARGET} PRIVATE ${UMICOM_FAT_DIRECTORY_DEFINITION})
        if(UMICOM_FAT_DIRECTORY_DEFINITIONS)
            target_compile_definitions(${UMICOM_FAT_DIRECTORY_TARGET} PRIVATE ${UMICOM_FAT_DIRECTORY_DEFINITIONS})
        endif()
        if(UMICOM_FAT_DIRECTORY_LIBRARIES)
            target_link_libraries(${UMICOM_FAT_DIRECTORY_TARGET} PRIVATE ${UMICOM_FAT_DIRECTORY_LIBRARIES})
        endif()
        target_link_options(${UMICOM_FAT_DIRECTORY_TARGET} PRIVATE ${UMICOM_FAT_DIRECTORY_LINK_OPTIONS}
            "-Wl,-Map,${CMAKE_CURRENT_BINARY_DIR}/${UMICOM_FAT_DIRECTORY_OUTPUT}.map")
        set_target_properties(${UMICOM_FAT_DIRECTORY_TARGET} PROPERTIES OUTPUT_NAME "${UMICOM_FAT_DIRECTORY_OUTPUT}"
            SUFFIX ".elf" RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/tests"
            LINK_DEPENDS "${UMICOM_KERNEL_LINKER_SCRIPT}")
        if(UMICOM_FAT_DIRECTORY_DEPENDENCIES)
            add_dependencies(${UMICOM_FAT_DIRECTORY_TARGET} ${UMICOM_FAT_DIRECTORY_DEPENDENCIES})
        endif()
    endforeach()
    # Add reverse dependencies after all snapshots so clones cannot depend on
    # themselves. kernel_current_image rebuilds every acceptance executable.
    add_dependencies(umicom-kernel umicom-fat16-directory-image umicom-fat16-directory-readback-image
        umicom-fat16-directory-interrupted-image umicom-fat16-directory-rejected-image)
    if(NOT UMICOM_QEMU_RISCV64)
        return()
    endif()
    set(UMICOM_FAT_DIRECTORY_FIXTURE_SOURCE "${CMAKE_CURRENT_SOURCE_DIR}/tests/fat16_file_commit/fixture.raw")
    file(SHA256 "${UMICOM_FAT_DIRECTORY_FIXTURE_SOURCE}" UMICOM_FAT_DIRECTORY_FIXTURE_HASH)
    if(NOT UMICOM_FAT_DIRECTORY_FIXTURE_HASH STREQUAL "538d4c1def74b0241a91a350362038a85934a9a5d522f86bd7c5347b44c3e1b5")
        message(FATAL_ERROR "The synthetic archive-clear FAT16 fixture does not match its recorded SHA-256.")
    endif()
    set(UMICOM_FAT_DIRECTORY_MAIN "${CMAKE_CURRENT_BINARY_DIR}/fixtures/umicom-fat16-directory.raw")
    set(UMICOM_FAT_DIRECTORY_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/cmake/Fat16Directory.cmake")
    set(UMICOM_FAT_DIRECTORY_BASE kernel.riscv64.fat16_directory)
    add_test(NAME ${UMICOM_FAT_DIRECTORY_BASE}_prepare COMMAND "${CMAKE_COMMAND}"
        "-DUMICOM_FAT_DIRECTORY_SOURCE=${UMICOM_FAT_DIRECTORY_FIXTURE_SOURCE}"
        "-DUMICOM_FAT_DIRECTORY_DISK=${UMICOM_FAT_DIRECTORY_MAIN}"
        -DUMICOM_FAT_DIRECTORY_STATE=0 -DUMICOM_FAT_DIRECTORY_ROLE=prepare -P "${UMICOM_FAT_DIRECTORY_SCRIPT}")
    set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_prepare PROPERTIES TIMEOUT 10
        FIXTURES_REQUIRED kernel_current_image FIXTURES_SETUP kernel_fat16_directory_fixture)
    set(UMICOM_FAT_DIRECTORY_PREVIOUS kernel_fat16_directory_fixture)
    # The earlier RANGE 1 9 covered directory allocation; 1 13 adds moves.
    foreach(UMICOM_FAT_DIRECTORY_STATE RANGE 1 13)
        list(GET UMICOM_FAT_DIRECTORY_PHASES ${UMICOM_FAT_DIRECTORY_STATE} UMICOM_FAT_DIRECTORY_PHASE)
        string(REPLACE "-" "_" UMICOM_FAT_DIRECTORY_SUFFIX "${UMICOM_FAT_DIRECTORY_PHASE}")
        set(UMICOM_FAT_DIRECTORY_REQUIRED "kernel_current_image;kernel_fat16_directory_fixture;${UMICOM_FAT_DIRECTORY_PREVIOUS}")
        if(UMICOM_FAT_DIRECTORY_STATE LESS 14)
            set(UMICOM_FAT_DIRECTORY_FORK "${CMAKE_CURRENT_BINARY_DIR}/fixtures/umicom-fat16-directory-${UMICOM_FAT_DIRECTORY_PHASE}-interrupted.raw")
            set(UMICOM_FAT_DIRECTORY_FORK_ID "kernel_fat16_directory_${UMICOM_FAT_DIRECTORY_SUFFIX}_fork")
            set(UMICOM_FAT_DIRECTORY_STAGED_ID "${UMICOM_FAT_DIRECTORY_FORK_ID}_staged")
            math(EXPR UMICOM_FAT_DIRECTORY_SOURCE_STATE "${UMICOM_FAT_DIRECTORY_STATE} - 1")
            add_test(NAME ${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_fork_prepare COMMAND "${CMAKE_COMMAND}"
                "-DUMICOM_FAT_DIRECTORY_SOURCE=${UMICOM_FAT_DIRECTORY_MAIN}" "-DUMICOM_FAT_DIRECTORY_DISK=${UMICOM_FAT_DIRECTORY_FORK}"
                "-DUMICOM_FAT_DIRECTORY_STATE=${UMICOM_FAT_DIRECTORY_SOURCE_STATE}" -DUMICOM_FAT_DIRECTORY_ROLE=prepare -P "${UMICOM_FAT_DIRECTORY_SCRIPT}")
            set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_fork_prepare PROPERTIES TIMEOUT 10
                FIXTURES_REQUIRED "${UMICOM_FAT_DIRECTORY_REQUIRED}" FIXTURES_SETUP "${UMICOM_FAT_DIRECTORY_FORK_ID}")
            # The main writer cannot mutate this checkpoint until the dirty
            # fork's prepare has copied and hashed every byte successfully.
            list(APPEND UMICOM_FAT_DIRECTORY_REQUIRED "${UMICOM_FAT_DIRECTORY_FORK_ID}")
            foreach(UMICOM_FAT_DIRECTORY_FORK_ROLE IN ITEMS interrupted rejected)
                if(UMICOM_FAT_DIRECTORY_FORK_ROLE STREQUAL "interrupted")
                    set(UMICOM_FAT_DIRECTORY_FORK_DEPENDENCY "${UMICOM_FAT_DIRECTORY_FORK_ID}")
                else()
                    set(UMICOM_FAT_DIRECTORY_FORK_DEPENDENCY "${UMICOM_FAT_DIRECTORY_FORK_ID};${UMICOM_FAT_DIRECTORY_STAGED_ID}")
                endif()
                add_test(NAME ${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_${UMICOM_FAT_DIRECTORY_FORK_ROLE}
                    COMMAND "${CMAKE_COMMAND}" "-DUMICOM_FAT_DIRECTORY_QEMU=${UMICOM_QEMU_RISCV64}"
                    "-DUMICOM_FAT_DIRECTORY_IMAGE=$<TARGET_FILE:umicom-fat16-directory-${UMICOM_FAT_DIRECTORY_FORK_ROLE}-image>"
                    "-DUMICOM_FAT_DIRECTORY_DISK=${UMICOM_FAT_DIRECTORY_FORK}" "-DUMICOM_FAT_DIRECTORY_STATE=${UMICOM_FAT_DIRECTORY_STATE}"
                    "-DUMICOM_FAT_DIRECTORY_ROLE=${UMICOM_FAT_DIRECTORY_FORK_ROLE}" -P "${UMICOM_FAT_DIRECTORY_SCRIPT}")
                set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_${UMICOM_FAT_DIRECTORY_FORK_ROLE}
                    PROPERTIES TIMEOUT 90 FIXTURES_REQUIRED "kernel_current_image;${UMICOM_FAT_DIRECTORY_FORK_DEPENDENCY}")
                if(UMICOM_FAT_DIRECTORY_FORK_ROLE STREQUAL "interrupted")
                    set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_interrupted
                        PROPERTIES FIXTURES_SETUP "${UMICOM_FAT_DIRECTORY_STAGED_ID}")
                endif()
            endforeach()
            add_test(NAME ${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_fork_cleanup COMMAND "${CMAKE_COMMAND}"
                "-DUMICOM_FAT_DIRECTORY_DISK=${UMICOM_FAT_DIRECTORY_FORK}" -DUMICOM_FAT_DIRECTORY_ROLE=cleanup -P "${UMICOM_FAT_DIRECTORY_SCRIPT}")
            set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_fork_cleanup
                PROPERTIES TIMEOUT 10 FIXTURES_CLEANUP "${UMICOM_FAT_DIRECTORY_FORK_ID}")
        endif()
        add_test(NAME ${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX} COMMAND "${CMAKE_COMMAND}"
            "-DUMICOM_FAT_DIRECTORY_QEMU=${UMICOM_QEMU_RISCV64}" "-DUMICOM_FAT_DIRECTORY_IMAGE=$<TARGET_FILE:umicom-fat16-directory-image>"
            "-DUMICOM_FAT_DIRECTORY_DISK=${UMICOM_FAT_DIRECTORY_MAIN}" "-DUMICOM_FAT_DIRECTORY_STATE=${UMICOM_FAT_DIRECTORY_STATE}"
            -DUMICOM_FAT_DIRECTORY_ROLE=writer -P "${UMICOM_FAT_DIRECTORY_SCRIPT}")
        set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX} PROPERTIES TIMEOUT 90
            FIXTURES_REQUIRED "${UMICOM_FAT_DIRECTORY_REQUIRED}" FIXTURES_SETUP "kernel_fat16_directory_clean_${UMICOM_FAT_DIRECTORY_STATE}")
        add_test(NAME ${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_readback COMMAND "${CMAKE_COMMAND}"
            "-DUMICOM_FAT_DIRECTORY_QEMU=${UMICOM_QEMU_RISCV64}" "-DUMICOM_FAT_DIRECTORY_IMAGE=$<TARGET_FILE:umicom-fat16-directory-readback-image>"
            "-DUMICOM_FAT_DIRECTORY_DISK=${UMICOM_FAT_DIRECTORY_MAIN}" "-DUMICOM_FAT_DIRECTORY_STATE=${UMICOM_FAT_DIRECTORY_STATE}"
            -DUMICOM_FAT_DIRECTORY_ROLE=readback -P "${UMICOM_FAT_DIRECTORY_SCRIPT}")
        set(UMICOM_FAT_DIRECTORY_PREVIOUS "kernel_fat16_directory_validated_${UMICOM_FAT_DIRECTORY_STATE}")
        set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_${UMICOM_FAT_DIRECTORY_SUFFIX}_readback PROPERTIES TIMEOUT 90
            FIXTURES_REQUIRED "kernel_current_image;kernel_fat16_directory_fixture;kernel_fat16_directory_clean_${UMICOM_FAT_DIRECTORY_STATE}"
            FIXTURES_SETUP "${UMICOM_FAT_DIRECTORY_PREVIOUS}")
    endforeach()
    add_test(NAME ${UMICOM_FAT_DIRECTORY_BASE}_cleanup COMMAND "${CMAKE_COMMAND}"
        "-DUMICOM_FAT_DIRECTORY_DISK=${UMICOM_FAT_DIRECTORY_MAIN}" -DUMICOM_FAT_DIRECTORY_ROLE=cleanup -P "${UMICOM_FAT_DIRECTORY_SCRIPT}")
    set_tests_properties(${UMICOM_FAT_DIRECTORY_BASE}_cleanup PROPERTIES TIMEOUT 10 FIXTURES_CLEANUP kernel_fat16_directory_fixture)
endfunction()
cmake_language(DEFER CALL UmicomConfigureFat16DirectoryImages)
